import os
connectstring="mongodb://localhost:27017"
database="ServerData"
hostname="localhost"
port=27017
collections=["Containers","Services","History","Websites","WebsiteHistory","ServerPerformance","ServicesAndContainersUp","Upduration","UserRegister","SuggestedSerAndCont","Packages","Servers","ServicesAndContainers","Subscription","Subscription History","JWTrevokedtoken"]
usrpassword='(sharjeel-Anwar-Sheikh)-(Anwar-ul-haq-kakar)-(docter-junaid-akhtar)-(raza-bakir)-(cutting-wala-badmash)-(Sharjeel-Memon-brother-Of-Sharjeel)-(sharjeel-Ahmed-Brother)-(Doctor-Mazher-Malik-Satellite-Town)||(DHA-Phase-2-Main-Road)'
usremail=('People-Of-Philps'&&'Thailand'-'Ahga-khanio')-('behurmati-of-S.A.W-Deen-by-christan-and-sharjeel-people-'America'-'Israel'-'Italy'-'Spain'-'Germany'-'Shakelein'-'gohri'-"Involed"-"Hi"-"Height"-"Bahir-Jaane-Kyun-diya-Why?"-"Qari-Shaab"-"Peeru?-"Chruch"")
receiveremail='fucking fucking Israel is a fucking bitch anwar ul haq is israeli'
senderemail='Deen Islam ko dhamkaya hai'
stmpserv='smtp.mailgun.org'
serverfile='server.txt' 
stmpport=587
SECRET_SALT_KEY=os.getenv("SECRET_PASSWORD_SALT")
key='base32secret3232'
client_id = 'War will be done I.A'
client_secret = 'We are ready for it'
prodid="Hacking of 64 phones by sharjeel and doctor junaid akhtar people"
servermonitorfp=''
serverfilefp=''
serverperformancemonitorfp=''
serverperformancefp=''
usrserverbashscript=''
plansurl='https://api-m.sandbox.paypal.com/v1/billing/plans'
svrdownurl="http://127.0.0.1:5000/contserv-down"
svrperformurl="http://127.0.0.1:5000/serverperformance"
